In [1]:
import pandas as pd

emp_df = pd.read_csv('D:/upgrad/EDA/employment-data.csv')

In [2]:
emp_df.head()

,Serial Number,Name of the Candidate,Resume ID,Postal Address,Telephone No.,Mobile No.,Date of Birth,Email,Work Experience,Resume Title,Current Location,Preferred Location,Current Employer,Current Designation,Annual Salary,U.G. Course,P. G. Course,Post P. G. Course,Last Active Date,Comment 1
0,1,eswaran.k.,2202ca2e0bf1584674,"1/403,NORTH STREET PALLAPATTI,SIVAKSI,VIRUDHU ...",91 44,8.908314e+09,'24 Sep 1984,eswaranke05@gmail.com,4 Year(s),power engineer,Chennai,Anywhere in South India,"JINDAL STAINLESS LIMITED,ODISHA",ASSISTENT ENGINEER,4.3,Diploma,P.D.C.,NaN,'08 Sep 2012,'08 Sep 2012
1,2,Raj,4ab9edcf1d929e2204,"21/10, Saradambal street, \r\r\nReddykuppam Ro...",NaN,9.994844e+09,'04 Feb 1986,m.raj.soft@gmail.com,4 Year(s),Mainframe,Chennai,"Anywhere in South India, Anywhere in East Indi...",IBM INDIA PRIVATE LIMITED,SYSTEM OPERATION SENIOR SPECIALIST,5.45,B.Tech/B.E.,NaN,NaN,'19 Sep 2012,'19 Sep 2012
2,3,arun kumar.v,00d88e536f048e2a42,"V. Arun Kumar,\r\r\n4/283, Malamanur,\r\r\nPot...",NaN,9.500445e+09,'12 Apr 1989,arunpgp@yahoo.co.in,2 Year(s),B.E(ECE) Working as a Maintenance Engineer,Salem,"Bangalore, Chennai, Chennai",Kamachi Sponge and Power Corporation Limited,Electrical Maintenance Engineer,2,B.Tech/B.E.,NaN,NaN,'21 Sep 2012,'21 Sep 2012
3,4,dhayalan,5b687d5a11bce58812,"Permanent Address : S/o.K.Sundaresan,Ariyalur",44,9.840720e+09,'21 May 1987,dhayalan8@yahoo.com,4 Year(s),Electrical Engineer-Diploma(EEE)-4Yrs Exp. in ...,Chennai,NaN,Akash Engineering,Site Supervisor Electrical,2.4,Diploma,NaN,NaN,'08 Sep 2012,'08 Sep 2012
4,5,SUMAN ROY,6ab3d45252407fb581,"somu_somu011@yahoo.co.in,Mysore",91 44 08213293121,9.345269e+09,'01 Feb 1983,somu_somu011@yahoo.co.in,4 Year(s),BE-MECH-4 yrs exp,Chennai,Anywhere in Northern India,BHEL,ENGINEER,10,B.Tech/B.E.,NaN,NaN,'08 Sep 2012,'08 Sep 2012